# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=40)),
                ('participant_surname', models.CharField(max_length=40)),
                ('participant_mail_addr', models.EmailField(max_length=30)),
            ],
        ),
    ]
