# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='participant_mail_addr',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
