# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='Backend', upload_to=event.models.upload_file),
            preserve_default=False,
        ),
    ]
