# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import speaker.models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='mission',
            field=models.CharField(default='Backend', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(upload_to=speaker.models.upload_file),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='slug',
            field=models.SlugField(editable=False, max_length=80, unique=True),
        ),
    ]
