# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorShipLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='level_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sponsorship.SponsorShipLevel'),
        ),
    ]
