# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0002_sponsorship_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='sponsorship_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
